files:
  input_directory:
#  input_stack: "/Users/cix56657/Datasets/11830/01122021_BrnoKrios_arctis_lam2_pos15.st"
  input_stack: "/Users/cix56657/Datasets/12482/20210608_Position_7.preali"
  input_csv:
    #mdoc_file:
    #frames_directory:
#  input_tilt: "/Users/cix56657/Datasets/11830/01122021_BrnoKrios_arctis_lam2_pos15.rawtlt"
  input_exposure:
  output_directory: "/Users/cix56657/Tmp/quinoa/12482/001"

experiment:
  collection_order:
    starting_angle: 0
    starting_direction: +1
    tilt_increment: 2
    group_of: 3
    exclude_start: false
    per_view_exposure: 3
  rotation_offset: 86
  tilt_offset:
  pitch_offset:
  voltage:
  amplitude:
  cs:
  phase_shift:
  astigmatism_value:
  astigmatism_angle:
  thickness: 100

preprocessing:
  run: false
  exclude_blank_views:
  exclude_view_indexes:

alignment:
  run: true
  fit_rotation_offset: true
  fit_tilt_offset: true
  fit_pitch_offset: true
  fit_phase_shift: false
  fit_astigmatism: false
  fit_thickness:
  do_coarse_alignment: false
  do_ctf_alignment: true
  do_refine_alignment: true

postprocessing:
  run: false
  resolution: 18
  save_aligned_stack: true
  reconstruct_tomogram: true
  reconstruct_mode: real # fourier or real
  reconstruct_weighting: radial # fourier, radial, sirt-15
  reconstruct_z_padding: 0

compute:
  device: cpu
  n_cpu_threads: 6
  register_input_stack:
  log_level: trace
