files:
  input_directory:
  input_stack: "/home/thomas/Projects/data/ribo/tilt1/tilt1.mrc"
  input_tlt:
  input_exposure:
  output_directory: "/home/thomas/Projects/quinoa/tests/ribo_ctf"

tilt_scheme:
  order:
    starting_angle: 0
    starting_direction: +1
    angle_increment: 3
    group: 3
    exclude_start: false
    per_view_exposure: 3
  rotation_offset:
  tilt_offset:
  elevation_offset:
  voltage:
  amplitude:
  cs:
  phase_shift:
  astigmatism_value:
  astigmatism_angle:

preprocessing:
  run:
  exclude_blank_views: false
  exclude_view_indexes: 0

alignment:
  run:
  fit_rotation_offset:
  fit_tilt_offset:
  fit_elevation_offset:
  fit_phase_shift: false
  fit_astigmatism: false
  use_pairwise_matching:
  use_projection_matching: false
  use_ctf_estimate:

reconstruction:
  run: false
  resolution: 20
  thickness:
  cube_size:

compute:
  device: gpu
  n_cpu_threads: 4
  log_level: debug
