files:
  input_directory:
  input_stack: "/home/thomas/Projects/thickness-tomogram/tilt6/tilt6.mrc"
  input_csv: "/home/thomas/Projects/quinoa/tests/craig_tilt6/tilt6.csv"
  input_tlt:
  input_exposure:
  output_directory: "/home/thomas/Projects/quinoa/tests/craig_tilt6"

experiment:
  collection_order:
    starting_angle: 0
    starting_direction: +1
    tilt_increment: 2
    group_of: 3
    exclude_start: false
    per_view_exposure: 3
  rotation_offset: 85
  tilt_offset:
  elevation_offset:
  voltage:
  amplitude:
  cs:
  phase_shift:
  astigmatism_value:
  astigmatism_angle:
  thickness: 190

preprocessing:
  run:
  exclude_blank_views: true
  exclude_view_indexes:

alignment:
  run: false
  fit_rotation_offset:
  fit_tilt_offset:
  fit_elevation_offset:
  fit_phase_shift:
  fit_astigmatism:
  use_initial_pairwise_alignment: true
  use_ctf_estimate: true
  use_thickness_estimate: true
  use_projection_matching: true
  rotation_spline_resolution: 3

postprocessing:
  run:
  save_aligned_stack:
  reconstruct_tomogram: true
  reconstruct_tomogram_resolution:
  reconstruct_cube_size:

compute:
  device: gpu
  n_cpu_threads: 8
  register_input_stack:
  log_level: trace
