files:
  input_directory:
  input_stack: "/home/thomas/Projects/data/ribo/tilt1/tilt1.mrc"
  input_tlt:
  input_exposure:
  output_directory: "/home/thomas/Projects/quinoa/tests/ribo_ctf"

experiment:
  collection_order:
    starting_angle: 0
    starting_direction: +1
    tilt_increment: 3
    group_of: 3
    exclude_start: false
    per_view_exposure: 3
  rotation_offset: 175
  tilt_offset:
  elevation_offset:
  voltage:
  amplitude:
  cs:
  phase_shift:
  astigmatism_value:
  astigmatism_angle:
  thickness: 80

preprocessing:
  run:
  exclude_blank_views: true
  exclude_view_indexes:

alignment:
  run:
  fit_rotation_offset:
  fit_tilt_offset:
  fit_elevation_offset:
  fit_phase_shift: false
  fit_astigmatism: false
  use_initial_pairwise_alignment: true
  use_ctf_estimate: false
  use_thickness_estimate: false
  use_projection_matching: false

reconstruction:
  run: false
  resolution: 20
  thickness:
  cube_size:

compute:
  device: gpu
  n_cpu_threads: 8
  register_input_stack:
  log_level: trace
