[files]
#mdoc_file = '~/Datasets/11830/01122021_BrnoKrios_arctis_lam2_pos15.mdoc'
#stack_file = '~/Datasets/11830/01122021_BrnoKrios_arctis_lam2_pos15.st'
#output_directory = '~/Tmp/quinoa/11830/pos15/001'
#frames_directory = '~/Datasets/11830'
#mdoc_file = '~/Datasets/11701/Cir_15kb_c_ts_005_driftcorr.mdoc'
#stack_file = '~/Datasets/11701/Cir_15kb_c_ts_005_driftcorr.st'
#output_directory = '~/Tmp/quinoa/11701/001'
#frames_directory = '~/Datasets/11701'

#mdoc_file = '~/Datasets/10304/file.mdoc'
#stack_file = '~/Datasets/10304/tilt1.mrc'
#output_directory = '~/Tmp/quinoa/10304/thickness'
#frames_directory = '~/Datasets/10304'

#mdoc_file = '~/Datasets/10304/file.mdoc'
#stack_file = '~/Datasets/10304/tilt6.mrc'
#output_directory = '~/Tmp/quinoa/10304/001/tilt6'
#frames_directory = '~/Datasets/10304'

#mdoc_file = '~/Datasets/Yakun/tilt9906.mdoc'
#stack_file = '~/Datasets/Yakun/tilt9906.mrc'
#output_directory = '~/Tmp/quinoa/Yakun/tilt9906/thickness_01'
#frames_directory = '~/Datasets/Yakun'
#csv_file = '~/Tmp/quinoa/Yakun/tilt9906/thickness_01/tilt9906_aligned.csv'

#mdoc_file = '~/Projects/synthetic_tomogram/tilt_series.mdoc'
#stack_file = '~/Projects/synthetic_tomogram/tilt_series_aligned.mrc'
#output_directory = '~/Projects/synthetic_tomogram3'
#frames_directory = '~/Projects/synthetic_tomogram'
#csv_file = '~/Projects/synthetic_tomogram3/tilt_series.csv'

## Remote
mdoc_file = '/dls/ebic/data/staff-scratch/thomas2/datasets/yakun/tilt9906.mdoc'
stack_file = '/dls/ebic/data/staff-scratch/thomas2/datasets/yakun/tilt9906.mrc'
output_directory = '/dls/ebic/data/staff-scratch/thomas2/tmp/yakun/tilt9906/recons04'
frames_directory = '/dls/ebic/data/staff-scratch/thomas2/datasets/yakun'
csv_file = '/dls/ebic/data/staff-scratch/thomas2/tmp/yakun/tilt9906/recons02/tilt9906_aligned.csv'

#output_directory = '/dls/ebic/data/staff-scratch/thomas2/tmp/10304/002/tilt1'
#frames_directory = '/dls/ebic/data/staff-scratch/thomas2/datasets/10304'
#mdoc_file = '/dls/ebic/data/staff-scratch/thomas2/datasets/10304/file.mdoc'
#stack_file = '/dls/ebic/data/staff-scratch/thomas2/datasets/10304/tilt1.mrc'

#mdoc_file = '/dls/ebic/data/staff-scratch/thomas2/datasets/11854/s001/s001.mdoc'
#stack_file = '/dls/ebic/data/staff-scratch/thomas2/datasets/11854/s001/s001.mrc'
#output_directory = '/dls/ebic/data/staff-scratch/thomas2/tmp/11854/s001/004'
#frames_directory = '/dls/ebic/data/staff-scratch/thomas2/datasets/11854/s001'

#mdoc_file = '/dls/ebic/data/staff-scratch/thomas2/datasets/11854/Y12_s003/Y12_s003.mdoc'
#stack_file = '/dls/ebic/data/staff-scratch/thomas2/datasets/11854/Y12_s003/Y12_s003.mrc'
#output_directory = '/dls/ebic/data/staff-scratch/thomas2/tmp/11854/Y12_s003/001'
#frames_directory = '/dls/ebic/data/staff-scratch/thomas2/datasets/11854/Y12_s003'

#mdoc_file = '/dls/ebic/data/staff-scratch/thomas2/datasets/11701/Cir_15kb_c_ts_005_driftcorr.mdoc'
#stack_file = '/dls/ebic/data/staff-scratch/thomas2/datasets/11701/Cir_15kb_c_ts_005_driftcorr.st'
#output_directory = '/dls/ebic/data/staff-scratch/thomas2/tmp/11701/004'
#frames_directory = '/dls/ebic/data/staff-scratch/thomas2/datasets/11701'

#mdoc_file = '/dls/ebic/data/staff-scratch/thomas2/datasets/10164/TS_03.mdoc'
#stack_file = '/dls/ebic/data/staff-scratch/thomas2/datasets/10164/TS_03_cropped.mrc'
#output_directory = '/dls/ebic/data/staff-scratch/thomas2/tmp/10164/TS_03/011'
#frames_directory = '/dls/ebic/data/staff-scratch/thomas2/datasets/10164'
#mdoc_file = '~/Datasets/10164/TS_03.mdoc'
#stack_file = '~/Datasets/10164/TS_03_cropped.mrc'
#output_directory = '~/Tmp/10164/TS_03/003'
#frames_directory = '~/Datasets/10164'

[experiment]
#tilt_axis = 175
#specimen_tilt = 0
#specimen_pitch = 0
voltage = 300
amplitude = 0.07
cs = 2.7
phase_shift = 0
thickness = 350

[preprocessing]
run = false
exclude_blank_views = true
exclude_stack_images = []

[alignment.coarse]
run = false
fit_rotation = true
fit_tilt = true

[alignment.ctf]
run = false
fit_rotation = false
fit_tilt = true
fit_pitch = true
fit_phase_shift = false
fit_astigmatism = true
fit_thickness = false

[alignment.refine]
run = false
fit_thickness = true

[postprocessing]
run = true
resolution = 18

stack.run = false
stack.correct_rotation = true
stack.interpolation = 'linear'
stack.dtype = 'f16'

tomogram.run = true
tomogram.correct_rotation = true
tomogram.interpolation = 'linear'
tomogram.dtype = 'f16'
tomogram.oversample = false
tomogram.correct_ctf = true
tomogram.z_padding_percent = 10
tomogram.phase_flip_strength = 8

[compute]
device = 'auto'
n_threads = 8
register_stack = true
log_level = 'trace'
