[data]
#mdocs = '/dls/ebic/data/staff-scratch/thomas2/projects/simulate_ctfs/SSS1/*.mdoc'
#stacks = '/dls/ebic/data/staff-scratch/thomas2/projects/simulate_ctfs/SSS1/*.mrc'
#rawtlts = '/dls/ebic/data/staff-scratch/thomas2/projects/simulate_ctfs/SSS1/*.rawtlt'
#output = '/dls/ebic/data/staff-scratch/thomas2/projects/simulate_ctfs/benchmarks/defaults'

mdocs = '/dls/ebic/data/staff-scratch/thomas2/datasets/10164/TS_03.mdoc'
stacks = '/dls/ebic/data/staff-scratch/thomas2/datasets/10164/TS_03_cropped.mrc'
rawtlts = '/dls/ebic/data/staff-scratch/thomas2/datasets/10164/TS_03.rawtlt'
output = '/dls/ebic/data/staff-scratch/thomas2/datasets/10164/quinoa_test'

#mdocs = '~/Datasets/10164/TS_03_clean.mdoc'
#stacks = '~/Datasets/10164/TS_03_clean.mrc'
##rawtlts = '~/Datasets/10164/TS_03_clean.rawtlt'
#output = '~/Datasets/10164/test_baseline'

#mdocs = '/dls/ebic/data/staff-scratch/thomas2/datasets/10700/tom1.mdoc'
#stacks = '/dls/ebic/data/staff-scratch/thomas2/datasets/10700/tom1.st'
#rawtlts = '/dls/ebic/data/staff-scratch/thomas2/datasets/10700/tom1.rawtlt'
#output = '/dls/ebic/data/staff-scratch/thomas2/datasets/10700/quinoa'

#mdocs = '/dls/ebic/data/staff-scratch/thomas2/datasets/10988/TS*.mdoc'
#stacks = '/dls/ebic/data/staff-scratch/thomas2/datasets/10988/TS*.st'
#rawtlts = '/dls/ebic/data/staff-scratch/thomas2/datasets/10988/TS*.rawtlt'
#output = '/dls/ebic/data/staff-scratch/thomas2/datasets/10988/quinoa'

#stack_file = '/dls/ebic/data/staff-scratch/thomas2/projects/simulate_ctfs/009/ts_04.mrc'
#mdoc_file = '/dls/ebic/data/staff-scratch/thomas2/projects/simulate_ctfs/009/ts_04.mdoc'
#output_directory = '/dls/ebic/data/staff-scratch/thomas2/projects/simulate_ctfs/009/quinoa/ts_04/fix_astig'

[experiment]
#tilt_axis = 80
#voltage = 300
#amplitude = 0.09
#cs = 2.7
#phase_shift = 0
#thickness = 150
#add_specimen_tilt = 3
#add_specimen_pitch = -5

[preprocessing]
run = false
#exclude_blank_views = true
#exclude_stack_indices = [0,1,2]

[alignment.coarse]
run = false
check_rotation = true
fit_rotation = true
fit_tilt = true
fit_pitch = true

[alignment.ctf]
run = true
patch_size_min_pix = 500
patch_size_ang = 500
resolution_range = [30, 4]
nb_images_in_initial_average = 3
max_nb_high_resolution_recovery = 0
astigmatism_tilt_resolution = [5, -4]
phase_shift_time_resolution = [2, 3]
check_defocus_gradient = true
fit_rotation = true
fit_tilt = true
fit_pitch = true
fit_astigmatism = true
fit_phase_shift = false
fit_thickness = false

[alignment.refine]
run = false
correct_ctf = true
phase_flip_strength = 8
fit_rotation = false
fit_tilt = true
fit_pitch = true
fit_thickness = true

[postprocessing]
run = false
resolution = 16

stack.run = true
stack.correct_rotation = false
stack.interpolation = 'linear'
stack.dtype = 'f16'

tomogram.run = true
tomogram.correct_rotation = true
tomogram.dtype = 'f16'
tomogram.algorithm = 'fourier-wbp' # or real-wp
tomogram.interpolation = 'linear'
tomogram.oversampling_factor = 4
tomogram.ramp_filter = false
tomogram.correct_ctf = true
tomogram.z_padding_percent = 10
tomogram.phase_flip_strength = 0.7

[compute]
device = 'auto'
n_threads = 16
register_stack = true
log_level = 'trace'
dry = false
stop_at_first_error = true
