[data] # ---------------------------------------------------------------------
# .mdoc files or directories containing .mdoc files. Glob patterns are supported. Overwritten by --mdocs.
#mdocs = <single-quoted-path-pattern>

# MRC or TIFF files containing the tilt images.
# If files are entered, they are each assigned to a mdoc based on their basename.
# If directories are entered, files with extension .mrc, .mrcs, or .st are searched and
# matched to a mdoc based on their basename.
# Glob patterns are supported. Overwritten by --stacks.
#stacks = <single-quoted-path-pattern>

# Files containing the tilt angles (one per line).
# If files are entered, they are each assigned to a mdoc based on their basename.
# If directories are entered, files with extension .rawtlt or .tlt are searched and
# matched to a mdoc based on their basename, and tilt angles should match the mdoc TiltAngle (within 0.1 degree).
# If not provided, stacks are assumed to be sorted in ascending order by their tilt angles and
# are required to have the same number of tilts as the mdoc.
# Glob patterns are supported. Overwritten by --rawtlts.
#rawtlts = <single-quoted-path-pattern>

# Base directory where the per-stack output directories are saved.
# Directories will be created if they don't exist.
# Defaults to the current working directory. Overwritten by --output.
#output = <single-quoted-path>

[experiment] # ---------------------------------------------------------------------
# Tilt-axis angle of the stacks (as specified in IMOD).
# If not provided, it is taken from the mdocs (not recommended).
# If unknown, see settings.alignment.coarse.check_rotation.
# Overwritten by --tilt-axis.
#tilt_axis = <in degrees>

# Energy of the electrons.
# If not provided, it is taken from the mdocs.
#voltage = <in keV>

# Amplitude contrast.
#amplitude = 0.07

# Spherical aberration, in mm.
#cs = 2.7

# Phase shift, in degrees.
#phase_shift = 0

# Estimate of the specimen thickness, in nm.
# If specified, it can improve robustness and accuracy of the fit.
#thickness = 0

# Add a fixed offset to the specimen inclination, in degrees.
#add_specimen_tilt = 0
#add_specimen_pitch = 0

[preprocessing] # ---------------------------------------------------------------------
run = false

# Exclude views with abnormal basic statistics.
#exclude_blank_views = true

# Indices, from 0, of the images in the stack to exclude. E.g. [0,1,41].
#exclude_stack_indices = []

[alignment.coarse] # ---------------------------------------------------------------------
# Whether to run the coarse image alignment step. Both the specimen orientation and image translations are updated.
run = false

# TODO Add doc
#check_rotation = true
#fit_rotation = false
#fit_tilt = true
#fit_pitch = true

[alignment.ctf] # ---------------------------------------------------------------------
# Whether to run the CTF alignment step. Both the specimen orientation and image translations are updated.
run = true

# Target patch size, in angstrom.
# Decreasing this may improve the quality of the spectrum, but will slow dow the alignment.
#patch_size_ang = 500

# Minimum patch size, in pixels. Used to make sure patches don't get too small with small pixel-sizes.
#patch_size_min_pix = 512

# Initial resolution [start, end] range of the power spectra, in angstrom.
#resolution_range = [30, 3]

# Number of power-spectra to average for the initial fitting.
# This is based on the lowest-tilt image.
#nb_images_in_initial_average = 3

# TODO Add doc
#max_nb_high_resolution_recovery = 0
#astigmatism_tilt_resolution = [5, -4]
#phase_shift_time_resolution = [2, 3]
#check_defocus_gradient = true
#fit_rotation = true
#fit_tilt = true
#fit_pitch = true
#fit_astigmatism = true
#fit_phase_shift = false
#fit_thickness = true

[alignment.refine] # ---------------------------------------------------------------------
run = false

# TODO Add doc
correct_ctf = true
phase_flip_strength = 8
fit_rotation = false
fit_tilt = true
fit_pitch = true
fit_thickness = true

[postprocessing] # ---------------------------------------------------------------------
run = false

# TODO Add doc
resolution = 16
stack.run = true
stack.correct_rotation = false
stack.interpolation = 'linear'
stack.dtype = 'f16'
tomogram.run = true
tomogram.correct_rotation = true
tomogram.dtype = 'f16'
tomogram.algorithm = 'fourier-wbp' # or real-wp
tomogram.interpolation = 'linear'
tomogram.oversampling_factor = 4
tomogram.ramp_filter = false
tomogram.correct_ctf = true
tomogram.z_padding_percent = 10
tomogram.phase_flip_strength = 0.7

[compute] # ---------------------------------------------------------------------
device = 'auto'
n_threads = 16
register_stack = true
log_level = 'trace'
dry = false
stop_at_first_error = true
